from enum import Enum


class JobStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    ASSIGNED = "ASSIGNED"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class NodeType(str, Enum):
    API_SERVER = "API_SERVER"
    ORCHESTRATOR = "ORCHESTRATOR"
    LLM_WORKER = "LLM_WORKER"
    LIBRARY_WORKER = "LIBRARY_WORKER"
